### ISSUE TITLE
Error: spawn compass ENOENT

### ISSUE THREAD

**Issue by user234683** [willcannings/live-dash-mse-player#1]
Hello, I'm looking for a lightweight DASH library for my app and want to try this one. I roughly did
```
$ sudo apt install npm
$ npm install
$ node bower install
$ sudo npm install --global gulp-cli (as specified here https://gulpjs.com/docs/en/getting-started/quick-start/ , since the gulp command was not installed by the previous step for some reason even though gulp was listed in npm list)
$ gulp serve
[20:40:00] Using gulpfile ~/Downloads/live-dash-mse-player-master/gulpfile.js
[20:40:00] Starting 'dev:js'...
[20:40:00] Starting 'dev:styles'...
[20:40:00] Finished 'dev:styles' after 19 ms
[20:40:00] Starting 'watch'...
[20:40:00] Finished 'watch' after 61 ms
[20:40:00] Starting 'browser-sync'...
[20:40:00] Finished 'browser-sync' after 48 ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn compass ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
`npm list` shows that gulp-compass is installed.

System:
```
Debian GNU/Linux 10
npm 6.14.10 (upgraded manually from the distribution version which was incompatible with the node version)
node v10.21.0
```

Is there any way to bypass gulp? I also tried concating both the src and dist files but either case resulted in errors on including the script. I'm new to Javascript development and tooling so apologies.

**Comment by user234683** [comment]
Okay I figured it out. `compass` is _not_ included with gulp-compass. gulp-compass appears to just be a wrapper. Compass seems to be a ruby program and so requires these commands to install (debian):
```
sudo apt install ruby-full
sudo gem install compass
```
